// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeletePostResponse struct {
	DeletedPostID int `json:"deletedPostId"`
}

type DeleteUserResponse struct {
	DeletedUserID int `json:"deletedUserId"`
}

type Mutation struct {
}

type Post struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

type PostInput struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}

type UserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
